export const STAFF_LOADING = 'STAFF_LOADING';
export const ADD_STAFF = 'ADD_STAFF';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const ADD_DEPARTMENT_STAFFS = 'ADD_DEPARTMENT_STAFFS';
export const DEPARTMENT_STAFFS_LOADING = 'DEPARTMENT_STAFFS_LOADING';
export const ADD_STAFFS_SALARY = 'ADD_STAFFS_SALARY';
export const STAFFS_SALARY_LOADING = 'STAFFS_SALARY_LOADING';
export const DEPARTMENT_STAFFS_FAIL = 'DEPARTMENT_STAFFS_FAIL';

